# Generated by Django 3.1.4 on 2021-12-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storegd', '0003_auto_20211209_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=False),
        ),
    ]
