# Generated by Django 3.1.4 on 2021-12-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storegd', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ditail',
        ),
    ]
