# Generated by Django 3.1.4 on 2021-12-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storegd', '0006_remove_product_ditail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ditail',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
