# Generated by Django 3.1.4 on 2021-12-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storegd', '0008_auto_20211210_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ditail',
            field=models.CharField(default=True, max_length=250, null=True),
        ),
    ]
